### ISSUE TITLE
Tap-spec

### ISSUE THREAD

**Issue by scottcorgan** [axross/tap-diff#1]
Any reason you didn't just open a pull request on tap-spec? (https://github.com/scottcorgan/tap-spec)

It seems like it would have been nice to collab on adding that feature to tap-spec instead of add more of the same to the ecosystem.

You did a great job though!

**Comment by axross** [comment]
@scottcorgan 

Thank you! :)
I started to create this reporter because I want the necessity minimum and human friendly reporter.
I think it is nice many choices to use [tape](https://github.com/substack/tape).
I appreciate your offer but let me think about it.

**Comment by blakeembrey** [comment]
I just started using this from `tap-spec`, really just need the diff ability to be able to use. I was dying testing five level deep nested objects and not able to see the diff - so thanks :smile: It would be cool to merge the functionality, I think a basic diff is necessary for checking test output, but I haven't found one that does a perfect job (yet).

**Comment by scottcorgan** [comment]
Checkout http://github.com/tap-format/spec. It's got the diff in there. Ultimately the predecessor to tap-spec

**Comment by blakeembrey** [comment]
* successor

Nice work! Just tried it and it does look great :+1: You should get some basic docs and a screenshot in there, I didn't realise that was even installable.

**Comment by scottcorgan** [comment]
Yes! Successor, thanks. I was mobile when responding!

**Comment by blakeembrey** [comment]
You're probably aware of this (I always forget) but the NPM version bundled with node 0.10 does not support scoped packages. You might want to make a note, since when I run tests they usually go down to 0.10.
